apiVersion: 'v1'
kind: 'Pod'
metadata:
  namespace: utils
  labels:
    jenkins-slave: jenkins-job-runner
  name: jenkins-job-runner
spec:
  imagePullSecrets:
    - name: registry-secret
  containers:
    - image: 'baamtu/jenkins-slave'
      name: jnlp
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      resources: {}
      tty: yes
    - name: dind-daemon
      image: docker:1.12.6-dind
      resources: {}
      tty: yes
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
  restartPolicy: Never
  securityContext: {}
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
    - emptyDir:
        medium: ''
      name: workspace-volume
